// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/purchase/create": {
            "post": {
                "description": "Create a new Purchase for detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "summary": "Create a new Purchase",
                "parameters": [
                    {
                        "description": "request for creating new purchase history",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.CreatePurchaseHistoryParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success create new Purchase",
                        "schema": {
                            "$ref": "#/definitions/internal.PurchaseHistory"
                        }
                    }
                }
            }
        },
        "/purchase/delete/{purchase_number}": {
            "delete": {
                "description": "Deletion proccess can only be done if it is not completed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "summary": "Delete Purchase",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "purchase ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete purchase",
                        "schema": {
                            "$ref": "#/definitions/api.DeletePurchaseSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/create": {
            "post": {
                "description": "Creating New User which never existed before",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create New User of App",
                "parameters": [
                    {
                        "description": "request for creating new user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "reponse if success creating new user",
                        "schema": {
                            "$ref": "#/definitions/api.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.CreateUserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal.CreateUserTxResult"
                },
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "api.DeletePurchaseSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal.DeletePurchaseItemsTxParams"
                },
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid request body"
                },
                "status_code": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "internal.CreatePurchaseHistoryParams": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "description": "Date              *time.Time ==\u003e auto generate from golang time.Date",
                    "type": "integer"
                },
                "purchase_number": {
                    "description": "PRCBOOK_20250421_RANDOMCHAR",
                    "type": "string"
                },
                "status": {
                    "description": "pending or completed",
                    "type": "string"
                },
                "total_price_payment": {
                    "type": "number"
                }
            }
        },
        "internal.CreateUserTxResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password_history_count": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal.DeletePurchaseItemsTxParams": {
            "type": "object",
            "properties": {
                "purchase_number": {
                    "type": "string"
                }
            }
        },
        "internal.PurchaseHistory": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "purchase_id": {
                    "type": "integer"
                },
                "purchase_number": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_price_payment": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger LukeAul API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
