basePath: /
definitions:
  api.CreateUserRequest:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - firstname
    - lastname
    - password
    - username
    type: object
  api.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/internal.CreateUserTxResult'
      message:
        type: string
      status_code:
        type: integer
    type: object
  api.DeletePurchaseSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/internal.DeletePurchaseItemsTxParams'
      message:
        type: string
      status_code:
        example: 200
        type: integer
    type: object
  api.ErrorResponse:
    properties:
      message:
        example: invalid request body
        type: string
      status_code:
        example: 400
        type: integer
    type: object
  internal.CreatePurchaseHistoryParams:
    properties:
      customer_id:
        description: Date              *time.Time ==> auto generate from golang time.Date
        type: integer
      purchase_number:
        description: PRCBOOK_20250421_RANDOMCHAR
        type: string
      status:
        description: pending or completed
        type: string
      total_price_payment:
        type: number
    type: object
  internal.CreateUserTxResult:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password_history_count:
        type: string
      username:
        type: string
    type: object
  internal.DeletePurchaseItemsTxParams:
    properties:
      purchase_number:
        type: string
    type: object
  internal.PurchaseHistory:
    properties:
      customer_id:
        type: integer
      date:
        type: string
      purchase_id:
        type: integer
      purchase_number:
        type: string
      status:
        type: string
      total_price_payment:
        type: number
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger LukeAul API
  version: "1.0"
paths:
  /purchase/create:
    post:
      consumes:
      - application/json
      description: Create a new Purchase for detail
      parameters:
      - description: request for creating new purchase history
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal.CreatePurchaseHistoryParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success create new Purchase
          schema:
            $ref: '#/definitions/internal.PurchaseHistory'
      summary: Create a new Purchase
      tags:
      - purchase
  /purchase/delete/{purchase_number}:
    delete:
      consumes:
      - application/json
      description: Deletion proccess can only be done if it is not completed
      parameters:
      - description: purchase ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success delete purchase
          schema:
            $ref: '#/definitions/api.DeletePurchaseSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Delete Purchase
      tags:
      - purchase
  /users/create:
    post:
      consumes:
      - application/json
      description: Creating New User which never existed before
      parameters:
      - description: request for creating new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: reponse if success creating new user
          schema:
            $ref: '#/definitions/api.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create New User of App
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
